//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobAlertManagerGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobAlertManagerGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=8fcc8bd2f2ef5161a4e58fe59ddc348f.
        /// </summary>
        public static string AttachmentSaveDirSelWord {
            get {
                return ResourceManager.GetString("AttachmentSaveDirSelWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=dc964a3a34a94636cd0cc04334c0debe.
        /// </summary>
        public static string AttachmentsWordQ {
            get {
                return ResourceManager.GetString("AttachmentsWordQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=17a4d185cc370cd9ae9f5fb59368569e.
        /// </summary>
        public static string BriefViewWord {
            get {
                return ResourceManager.GetString("BriefViewWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=639538d42ec79b8dd689f1ecd8ae4d14.
        /// </summary>
        public static string CGWEMailReaderTitleWord {
            get {
                return ResourceManager.GetString("CGWEMailReaderTitleWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=f15c1cae7882448b3fb0404682e17e61.
        /// </summary>
        public static string ContentWord {
            get {
                return ResourceManager.GetString("ContentWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=5fff2435440986880b9d0a7ffa4345a9.
        /// </summary>
        public static string ConversationThreadWord {
            get {
                return ResourceManager.GetString("ConversationThreadWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=a927d82856c3de5786d8d716af7e918f.
        /// </summary>
        public static string DispositionNotificationWord {
            get {
                return ResourceManager.GetString("DispositionNotificationWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=28a6b3b8b5f326fbacb9cf1a184541d6.
        /// </summary>
        public static string EMailThreadViewerWord {
            get {
                return ResourceManager.GetString("EMailThreadViewerWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=13721617f8a6508cb9fbacec9617da45.
        /// </summary>
        public static string FileExistWarningWords {
            get {
                return ResourceManager.GetString("FileExistWarningWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=a62fee69552ef2444aec70c86e159694.
        /// </summary>
        public static string MailPropertiesWord {
            get {
                return ResourceManager.GetString("MailPropertiesWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=85a931025818c854abbddbb5484e3d91.
        /// </summary>
        public static string MsgBccQWord {
            get {
                return ResourceManager.GetString("MsgBccQWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=82e9ef5cbcf6244917358e3b56a24cab.
        /// </summary>
        public static string MsgCcQWord {
            get {
                return ResourceManager.GetString("MsgCcQWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=1e6d57e813355689e9c77e947d73ad8f.
        /// </summary>
        public static string MsgFromQWord {
            get {
                return ResourceManager.GetString("MsgFromQWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=47a0be8d1015d526a1fbaa56c3102135.
        /// </summary>
        public static string MsgSubjectQWord {
            get {
                return ResourceManager.GetString("MsgSubjectQWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=33caa076f23f453dd4061726f3706325.
        /// </summary>
        public static string MsgToQWord {
            get {
                return ResourceManager.GetString("MsgToQWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=49ee3087348e8d44e1feda1917443987.
        /// </summary>
        public static string NameWord {
            get {
                return ResourceManager.GetString("NameWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=4aca7c877c2dc5f6ba3d9e6cd1e61739.
        /// </summary>
        public static string OpenViewWindowDDDToolTip {
            get {
                return ResourceManager.GetString("OpenViewWindowDDDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=3bf6a0facffe3fd925a1be386b6aab87.
        /// </summary>
        public static string OtherInfoWord {
            get {
                return ResourceManager.GetString("OtherInfoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=9dffbf69ffba8bc38bc4e01abf4b1675.
        /// </summary>
        public static string PlainTextWord {
            get {
                return ResourceManager.GetString("PlainTextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=31fde7b05ac8952dacf4af8a704074ec.
        /// </summary>
        public static string PreviewWord {
            get {
                return ResourceManager.GetString("PreviewWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=65e65c8ab0d8609ce12fc68a03cb8e00.
        /// </summary>
        public static string RawTextWord {
            get {
                return ResourceManager.GetString("RawTextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=34d3e95b7df44d62f685eaf95d823c92.
        /// </summary>
        public static string ReceivedDateTimeQWord {
            get {
                return ResourceManager.GetString("ReceivedDateTimeQWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=84c4dfc8fccf9350a9610e366ae769a5.
        /// </summary>
        public static string ReplyToWord {
            get {
                return ResourceManager.GetString("ReplyToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=3135f4019bee015e2d1ae7f77f9f3f64.
        /// </summary>
        public static string RichTextWord {
            get {
                return ResourceManager.GetString("RichTextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=306971af3c5701fc47274333af5932cb.
        /// </summary>
        public static string RoutingInfoWord {
            get {
                return ResourceManager.GetString("RoutingInfoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=751e01e2e066b5ef28a0311da71a5785.
        /// </summary>
        public static string SaveAttachmentWord {
            get {
                return ResourceManager.GetString("SaveAttachmentWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=c9cc8cce247e49bae79f15173ce97354.
        /// </summary>
        public static string SaveWord {
            get {
                return ResourceManager.GetString("SaveWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=bc7234d92dd874189421dad4b7ceabf0.
        /// </summary>
        public static string ShowMessageThreadDDDToolTip {
            get {
                return ResourceManager.GetString("ShowMessageThreadDDDToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=5e51256d7e4970f95cef0aa4fcdadbf9.
        /// </summary>
        public static string ShowSequenceNumWord {
            get {
                return ResourceManager.GetString("ShowSequenceNumWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=71652f454a93fb8a35628c1b21134338.
        /// </summary>
        public static string SubMessageFoundDDDTip {
            get {
                return ResourceManager.GetString("SubMessageFoundDDDTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=c2b434398baf306cf5bc84a4e697d7dc.
        /// </summary>
        public static string SubMessagesWord {
            get {
                return ResourceManager.GetString("SubMessagesWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guid=0eaadb4fcb48a0a0ed7bc9868be9fbaa.
        /// </summary>
        public static string WarningWord {
            get {
                return ResourceManager.GetString("WarningWord", resourceCulture);
            }
        }
    }
}
